# workflow
name: SOX日报推送

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-sox:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v6  # 从 v4 改成 v6
      
      - name: 安装 Python
        uses: actions/setup-python@v6  # 从 v5 改成 v6
        with:
          python-version: '3.11'
      
      - name: 安装依赖
        run: pip install -r requirements.txt
      
      - name: 运行脚本
        env:
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
        run: python sox_daily.py
